DO $$
DECLARE
  v_branch_id UUID;
  v_customer_id UUID;
  v_product_id UUID;
  v_tx_id TEXT;  -- Using TEXT for transaction ID
  v_result RECORD;
BEGIN
  RAISE NOTICE 'Starting Atomic Delivery Verification (TEXT ID)...';

  -- 1. Setup Data: Get existing branch, customer, product
  SELECT id INTO v_branch_id FROM branches LIMIT 1;
  SELECT id INTO v_customer_id FROM customers LIMIT 1;
  SELECT id INTO v_product_id FROM products LIMIT 1;

  IF v_branch_id IS NULL THEN
    RAISE EXCEPTION 'No branch found';
  END IF;
  IF v_customer_id IS NULL THEN
     -- Try to find a profile to use as customer or just ANY customer
     SELECT id INTO v_customer_id FROM customers LIMIT 1;
     IF v_customer_id IS NULL THEN
        RAISE NOTICE 'No customer found, cannot create transaction';
        RETURN;
     END IF;
  END IF;
  
  RAISE NOTICE 'Using Branch: %, Product: %', v_branch_id, v_product_id;

  -- 2. Create Transaction (Letting DB generate ID or using manual if needed)
  -- Assuming ID is generated by default (TRX-...)
  INSERT INTO transactions (
    branch_id, 
    customer_id, 
    date, 
    status, 
    total_amount, 
    payment_amount, 
    change_amount, 
    payment_method, 
    is_office_sale,
    created_at,
    updated_at
  )
  VALUES (
    v_branch_id, 
    v_customer_id, 
    NOW(), 
    'pending', 
    50000, 
    0, 
    0, 
    'cash', 
    false,
    NOW(),
    NOW()
  )
  RETURNING id INTO v_tx_id;

  RAISE NOTICE 'Created Transaction with ID: % (Type: %)', v_tx_id, pg_typeof(v_tx_id);

  -- 3. Execute process_delivery_atomic RPC
  RAISE NOTICE 'Executing process_delivery_atomic...';
  
  SELECT * INTO v_result FROM process_delivery_atomic(
    v_tx_id,                           -- p_transaction_id (TEXT)
    jsonb_build_array(                 -- p_items
      jsonb_build_object(
        'product_id', v_product_id,
        'quantity', 1,
        'product_name', 'Test Product',
        'unit', 'pcs',
        'is_bonus', false,
        'notes', 'Test Delivery Item'
      )
    ),
    v_branch_id,                       -- p_branch_id
    NULL,                              -- p_driver_id
    NULL,                              -- p_helper_id
    CURRENT_DATE,                      -- p_delivery_date
    'Test Atomic Delivery',            -- p_notes
    NULL                               -- p_photo_url
  );

  -- 4. Verify Results
  RAISE NOTICE 'RPC Result: Success=%, DeliveryID=%, Error=%', v_result.success, v_result.delivery_id, v_result.error_message;

  IF v_result.success THEN
    RAISE NOTICE '✅ TEST PASSED: Delivery created successfully.';
  ELSE
    RAISE NOTICE '❌ TEST FAILED: %', v_result.error_message;
  END IF;

END $$;
